### ISSUE TITLE
Adapter terminates after upgrade Node to v16.3

### ISSUE THREAD

**Issue by Pix---** [ioBroker/ioBroker.cloud#203]
**Issue:**
Adapter stops 
```
2021-06-16 21:03:54.362  - [32minfo[39m: host.MacMini.local "system.adapter.cloud.0" enabled
2021-06-16 21:03:54.510  - [32minfo[39m: host.MacMini.local instance system.adapter.cloud.0 started with pid 63524
2021-06-16 21:03:55.927  - [32minfo[39m: cloud.0 (63524) starting. Version 4.0.11 in /usr/local/iobroker/node_modules/iobroker.cloud, node: v16.3.0, js-controller: 3.2.16
2021-06-16 21:04:15.938  - [32minfo[39m: cloud.0 (63524) Connecting with https://iobroker.pro:10555 with "@pro_xxxx@xxxx.com_xxxxx-xxxx-xxxx-xxxx-xxxxxxxxx"
2021-06-16 21:04:16.057  - [32minfo[39m: cloud.0 (63524) Trying to connect as system.user.admin
2021-06-16 21:04:16.155  - [31merror[39m: cloud.0 (63524) uncaught exception: Cannot read property 'isValidUTF8' of undefined
2021-06-16 21:04:16.155  - [31merror[39m: cloud.0 (63524) TypeError: Cannot read property 'isValidUTF8' of undefined
    at /usr/local/iobroker/node_modules/ws/lib/Receiver.js:532:29
    at Receiver.applyExtensions (/usr/local/iobroker/node_modules/ws/lib/Receiver.js:371:5)
    at /usr/local/iobroker/node_modules/ws/lib/Receiver.js:508:14
    at Receiver.flush (/usr/local/iobroker/node_modules/ws/lib/Receiver.js:347:3)
    at Receiver.finish (/usr/local/iobroker/node_modules/ws/lib/Receiver.js:541:12)
    at Receiver.expectHandler (/usr/local/iobroker/node_modules/ws/lib/Receiver.js:499:31)
    at Receiver.add (/usr/local/iobroker/node_modules/ws/lib/Receiver.js:103:24)
    at TLSSocket.realHandler (/usr/local/iobroker/node_modules/ws/lib/WebSocket.js:825:20)
    at TLSSocket.emit (node:events:394:28)
    at TLSSocket.emit (node:domain:470:12)
2021-06-16 21:04:16.156  - [31merror[39m: cloud.0 (63524) Cannot read property 'isValidUTF8' of undefined
2021-06-16 21:04:16.172  - [32minfo[39m: cloud.0 (63524) terminating
```

**Versions:**  
 - Adapter version: 4.0.11
 - JS-Controller version: 3.2.16
 - Node version: 16.3.0
 - Operating system: OS X Sierra

**Additional context**  
Issue started after upgrading NodeJS from v14 to v16
Tried to fix with reinstall

**Comment by GermanBluefox** [comment]
Should work with 4.1.0
