### ISSUE TITLE
Addon DashUI  can't render tplJscolor w00114 on "Wohnzimmer"

### ISSUE THREAD

**Issue by ManuelKlimek** [ioBroker/ioBroker.cloud#236]
```
2021-09-28 18:51:23.333  - error: cloud.0 (8032) Addon DashUI  can't render tplJscolor w00114 on "Wohnzimmer":
--
2021-09-28 18:51:23.334  - error: cloud.0 (8032) Addon DashUI  0 - TypeError: str.match is not a functionTypeError: str.match is not a function
2021-09-28 18:51:23.336  - error:  cloud.0 (8032) Addon DashUI  1 -     at jscolor.fromString  (file:///android_asset/www/widgets/colorpicker/js/jscolor.js:1190:17)
2021-09-28 18:51:23.339  - error: cloud.0 (8032) Addon DashUI  2 -     at _rgbChanged (file:///android_asset/www/index.html:4872:28)
2021-09-28 18:51:23.342  - error: cloud.0 (8032) Addon DashUI  3 -     at Object.jscolor (file:///android_asset/www/index.html:4877:17)
2021-09-28 18:51:23.347  - error: cloud.0 (8032) Addon DashUI  4 -     at Object.eval (tplJscolor.js:53:83)
2021-09-28 18:51:23.353  - error: cloud.0 (8032) Addon DashUI  5 -     at Function. (file:///android_asset/www/lib/js/can.custom.min.js:64:6166)
2021-09-28 18:51:23.362  - error: cloud.0 (8032) Addon DashUI  6 -     at Object.a.each (file:///android_asset/www/lib/js/can.custom.min.js:24:294)
2021-09-28 18:51:23.364  - error: cloud.0 (8032) Addon DashUI  7 -     at file:///android_asset/www/lib/js/can.custom.min.js:64:6147
2021-09-28 18:51:23.367  - error: cloud.0 (8032) Addon DashUI  8 -     at HTMLInputElement. (file:///android_asset/www/lib/js/can.custom.min.js:58:1841)
2021-09-28 18:51:23.369  - error: cloud.0 (8032) Addon DashUI  9 -     at Object.a.each (file:///android_asset/www/lib/js/can.custom.min.js:24:294)
2021-09-28 18:51:23.370  - error: cloud.0 (8032) Addon DashUI  10 -     at Function.hookup (file:///android_asset/www/lib/js/can.custom.min.js:58:1751)
```

**Comment by Apollon77** [comment]
Is it working qith DashUI in your local network? if not please ope issue there. If yes please state the adapter version you use locally

**Comment by ManuelKlimek** [comment]
> 
> 
> Is it working qith DashUI in your local network? if not please ope issue there. If yes please state the adapter version you use locally

Ich weis nicht was das Dash sein sollte.
Es existiert nicht.
Habe auch in der Vis nach dem w00114 gesucht und nicht gefunden.

**Comment by Apollon77** [comment]
Ok, was genau rufst DU denn auf? Ist es Vis ioder wie ist der relevante Visu Adapter benannt den du aufrufen willst?

**Comment by ManuelKlimek** [comment]
Laut dem 1. Fehler Code bin ich von der vis ausgegangen.

error: cloud.0 (8032) Addon DashUI  can't render tplJscolor w00114 on "Wohnzimmer":

Aber ich finde dort weder das DashUI noch den w00114 da ich wo ich meine das es sich hier um ein widget handelt.

Was mich verwundert es wurde nichts geändert oder bearbeit auch kein Update oder sonstiges es kam von jetzt auf gleich seit gestern gegen 16:30
