### ISSUE TITLE
WhiteList for Services not shown under Admin 5

### ISSUE THREAD

**Issue by mcuiobroker** [ioBroker/ioBroker.cloud#319]
Admin 4
![image](https://user-images.githubusercontent.com/84818934/183263855-3590e863-e165-4750-a17b-d4c222db2e4a.png)
Admin 5
![image](https://user-images.githubusercontent.com/84818934/183263864-49b94e83-a7fa-4ebe-8e83-d235518841f5.png)

**Comment by GermanBluefox** [comment]
Ich kann das nicht reproduzieren. Bei mir geht alles:
![cloud](https://user-images.githubusercontent.com/4582016/186383137-4c91fae3-5ce9-4f58-bb4b-d53704700d70.gif)

**Comment by bahnuhr** [comment]
Hallo bluefox.
Ich komme nicht in die Zeile um etwas eizugeben.
Ich kann da überall klicken.
Die Zeile zum Eingeben öffnet sich nicht.

**Comment by mcuiobroker** [comment]
Unter Admin 6 ist es wieder eingebbar.
![image](https://user-images.githubusercontent.com/84818934/186404218-4c33a560-ac02-4af2-a644-f3594d989e0d.png)

**Comment by bahnuhr** [comment]
Habe eben cloud 4.2.2. installiert.
Unter Admin 5 klappt es noch nicht.
Probiere jetzt mal update auf admin 6

**Comment by bahnuhr** [comment]
Oh mann,
jetzt starten meine javascript Instanzen nicht mehr. Sie bleiben rot.
Es kommt:
adapter "javascript" seems to be installed for a different version of Node.js. Trying to rebuild it... 1 attempt

**Comment by bahnuhr** [comment]
4.2.2.
cloud öffnet sich nicht mehr.
Bei F12 kommt folgendes:

instrument.ts:123 TypeError: to.map is not a function
    at Is.render (ChipInput.jsx:553:38)
    at Wi (react-dom.production.min.js:204:189)
    at Rs (react-dom.production.min.js:203:149)
    at oa (react-dom.production.min.js:292:172)
    at ra (react-dom.production.min.js:280:389)
    at Jc (react-dom.production.min.js:280:320)
    at ml (react-dom.production.min.js:280:180)
    at iu (react-dom.production.min.js:271:88)
    at ea (react-dom.production.min.js:273:300)
    at hn (react-dom.production.min.js:127:105)
    at bc (react-dom.production.min.js:283:470)
    at $n (react-dom.production.min.js:281:398)
    at bs (react-dom.production.min.js:270:269)
    at Ln (scheduler.production.min.js:13:203)
    at MessagePort.Gn (scheduler.production.min.js:14:128)

**Comment by bahnuhr** [comment]
Nachtrag:
cloud musste komplett gelöscht und danach neu installiert werden.
Daten manuell eingeben.
Das hat dann geklappt.
whitelist ist nun auch bei mir ersichtlich.

**Comment by Baenker** [comment]
da das Problem ja nicht mehr besteht, könnte man den Issue schließen?
