### ISSUE TITLE
Cloud adapter crash when changing level

### ISSUE THREAD

**Issue by modmax** [ioBroker/ioBroker.cloud#43]
Hi have a hue lamp and want to swith the lamp on or off (via "Alexa, schalte Wohnzimmer aus").
See error message below.
The datapoint has been created with cloud adapter and also the alexa smart home devices are dropped and readded after installing the newest version from github.

```
host`.iobroker | 2018-01-07 21:22:04.785 | error | instance system.adapter.cloud.0 terminated with code 0 (OK)
Caught | 2018-01-07 21:22:04.785 | error | by controller[0]:     at Decoder.Emitter.emit (/work/iobroker/node_modules/component-emitter/index.js:134:20)
Caught | 2018-01-07 21:22:04.785 | error | by controller[0]:     at Decoder. (/work/iobroker/node_modules/component-bind/index.js:21:15)
Caught | 2018-01-07 21:22:04.785 | error | by controller[0]:     at Manager.ondecoded (/work/iobroker/node_modules/socket.io-client/lib/manager.js:332:8)
Caught | 2018-01-07 21:22:04.785 | error | by controller[0]:     at Manager.Emitter.emit  (/work/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
Caught | 2018-01-07 21:22:04.785 | error | by controller[0]:     at Manager. (/work/iobroker/node_modules/component-bind/index.js:21:15)
Caught | 2018-01-07 21:22:04.785 | error | by controller[0]:     at Socket.onpacket (/work/iobroker/node_modules/socket.io-client/lib/socket.js:228:12)
Caught | 2018-01-07 21:22:04.785 | error | by controller[0]:     at Socket.onevent (/work/iobroker/node_modules/socket.io-client/lib/socket.js:270:10)
Caught | 2018-01-07 21:22:04.785 | error | by controller[0]:     at Socket.Emitter.emit  (/work/iobroker/node_modules/socket.io-client/node_modules/component-emitter/index.js:133:20)
Caught | 2018-01-07 21:22:04.785 | error | by controller[0]:     at Socket. (/work/iobroker/node_modules/iobroker.cloud/main.js:558:22)
Caught | 2018-01-07 21:22:04.785 | error | by controller[0]:     at AlexaSH2.process (/work/iobroker/node_modules/iobroker.cloud/lib/alexaSmartHomeV2.js:1387:75)
Caught | 2018-01-07 21:22:04.785 | error | by controller[0]: TypeError: Cannot read property 'hue.0.Philips_hue.WZ_Deckenleuchte.level' of undefined
```
![huelamp](https://user-images.githubusercontent.com/3912027/34653789-92f7439a-f3f1-11e7-86cc-f02500292c83.png)

```
{
  "_id": "hue.0.Philips_hue.WZ_Deckenleuchte.level",
  "type": "state",
  "common": {
    "name": "Philips_hue.WZ_Deckenleuchte.level",
    "read": true,
    "write": true,
    "type": "number",
    "role": "level.dimmer",
    "min": 0,
    "max": 100,
    "custom": {
      "cloud.0": {
        "smartName": {
          "de": "Wohnzimmer",
          "byON": "stored",
          "smartType": "LIGHT"
        }
      }
    }
  },
  "native": {
    "id": "5"
  },
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.hue.0",
  "ts": 1514396496879
}
```

**Comment by modmax** [comment]
The switching on/off for hue lamps just works if you also add the on-state. Then no error occurs.
![huelamp](https://user-images.githubusercontent.com/3912027/34653957-cbf6c226-f3f4-11e7-8549-72dd0ba02791.png)
But in older version (since cloud adapter 2.1.0) this also worked with just the level, when switching on/off a lamp with alexa call.
