### ISSUE TITLE
Smarte Geräte lassen sich nicht löschen

### ISSUE THREAD

**Issue by eXplOiD1** [ioBroker/ioBroker.cloud#53]
Guten Morgen,
in der Version 2.3.0 lassen sich die Smarten Geräte nicht löschen.
`global.js:76 Uncaught TypeError: Cannot read property 'open' of undefined
    at HTMLDivElement.<anonymous> (https://**********:9081/lib/js/materialize.js:1486:19)
    at Function.each (https://**********:9081/lib/js/jquery-1.11.1.min.js:2:2973)
    at m.fn.init.each (https://**********9081/lib/js/jquery-1.11.1.min.js:2:835)
    at m.fn.init.jQuery.fn.(anonymous function) [as modal] (https://**********:9081/lib/js/materialize.js:1484:21)
    at confirmMessage (https://**********:9081/js/adapter-settings.js:517:20)
    at HTMLButtonElement.<anonymous> (https://**********:9081/adapter/cloud/?0:284:21)
    at HTMLButtonElement.dispatch (https://**********:9081/lib/js/jquery-1.11.1.min.js:3:8440)
    at HTMLButtonElement.r.handle (https://**********:9081/lib/js/jquery-1.11.1.min.js:3:5143)`

**Comment by GermanBluefox** [comment]
Use 3.0.12 admin and do not show here you URLs !!!!
:)

**Comment by eXplOiD1** [comment]
ok danke.
im alten admin hat es funktioniert.
aber die beta lässt sich nicht auf 3.0.12 updaten ;)
$ ./iobroker url "https://github.com/ioBroker/ioBroker.admin-beta/tarball/master" admin-beta
install https://github.com/ioBroker/ioBroker.admin-beta/tarball/master
npm install https://github.com/ioBroker/ioBroker.admin-beta/tarball/master --production --prefix "/mnt/iobroker" (System call)
npm ERR! fetch failed https://github.com/ioBroker/ioBroker.admin-beta/tarball/master
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://github.com/ioBroker/ioBroker.admin-beta/tarball/masternpm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404

**Comment by GermanBluefox** [comment]
It is wrong way for update. You must write: `npm i iobroker.admin-beta` in /opt/iobroker

**Comment by GermanBluefox** [comment]
Will be closed. No answer.
